<?php $livrables = $livrables ?? []; ?>

<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div><p class="mb-2 text-xs uppercase tracking-[0.24em] text-gray-400">Projet</p><h2 class="font-display text-2xl font-bold text-primary-900"><?php echo htmlspecialchars($title ?? 'Projet', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></h2></div>
        <a href="<?php echo BASE_URL; ?>projet" class="inline-flex w-fit items-center justify-center gap-2 rounded-2xl border border-gray-200 bg-white px-4 py-3 text-sm font-semibold text-primary-900 shadow-sm hover:bg-primary-50 transition"><i data-lucide="arrow-left" class="h-4 w-4"></i>Retour aux projets</a>
    </div>
    <?php if (!empty($projet)): ?>
        <section class="rounded-3xl border border-gray-100 bg-white p-6 shadow-sm lg:p-8">
            <div class="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div><span class="mb-4 inline-flex rounded-full bg-primary-50 px-3 py-1 text-xs font-semibold text-primary-800"><?php echo htmlspecialchars($projet['statut'] ?? '-', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></span><h1 class="font-display text-3xl font-bold text-primary-900"><?php echo htmlspecialchars($projet['nom'] ?? '-', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></h1><p class="mt-3 text-sm text-gray-500"><?php echo htmlspecialchars(($projet['client_nom'] ?? '-') . ' · ' . ($projet['type_campagne'] ?? '-'), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p></div><div class="flex h-20 w-20 items-center justify-center rounded-[1.75rem] bg-primary-50 text-primary-800"><i data-lucide="target" class="h-9 w-9"></i></div></div>
            <div class="mt-8 grid gap-4 md:grid-cols-4"><div class="rounded-2xl bg-gray-50 p-4"><p class="text-xs uppercase tracking-[0.18em] text-gray-400">Budget</p><p class="mt-2 font-bold text-primary-900"><?php echo htmlspecialchars(number_format((float)($projet['budget'] ?? 0), 2, ',', ' '), ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p></div><div class="rounded-2xl bg-gray-50 p-4"><p class="text-xs uppercase tracking-[0.18em] text-gray-400">Debut</p><p class="mt-2 font-bold text-primary-900"><?php echo htmlspecialchars($projet['date_debut'] ?? '-', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p></div><div class="rounded-2xl bg-gray-50 p-4"><p class="text-xs uppercase tracking-[0.18em] text-gray-400">Fin</p><p class="mt-2 font-bold text-primary-900"><?php echo htmlspecialchars($projet['date_fin'] ?? '-', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p></div><div class="rounded-2xl bg-gray-50 p-4"><p class="text-xs uppercase tracking-[0.18em] text-gray-400">Livrables</p><p class="mt-2 text-2xl font-bold text-primary-900"><?php echo count($livrables); ?></p></div></div>
        </section>
        <section class="rounded-3xl border border-gray-100 bg-white p-6 shadow-sm"><h3 class="mb-4 text-lg font-semibold text-primary-900">Livrables</h3><?php if (!empty($livrables)): ?><div class="space-y-3"><?php foreach ($livrables as $livrable): ?><div class="rounded-2xl border border-gray-100 p-4"><div class="flex items-center justify-between gap-4"><p class="font-semibold text-primary-900"><?php echo htmlspecialchars($livrable['titre'] ?? '-', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p><span class="rounded-full bg-primary-50 px-3 py-1 text-xs font-semibold text-primary-800"><?php echo htmlspecialchars($livrable['statut'] ?? '-', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></span></div><p class="mt-1 text-sm text-gray-500"><?php echo htmlspecialchars($livrable['date_echeance'] ?? '-', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?></p></div><?php endforeach; ?></div><?php else: ?><p class="text-sm text-gray-500">Aucun livrable pour ce projet.</p><?php endif; ?></section>
    <?php else: ?>
        <section class="rounded-3xl border border-gray-100 bg-white p-10 text-center shadow-sm"><h3 class="font-display text-xl font-bold text-primary-900">Projet introuvable</h3></section>
    <?php endif; ?>
</div>
<script>if (typeof renderIcons === 'function') renderIcons();</script>
